# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# 1) Proxy all /api/* calls to your Render backend
[[redirects]]
  from   = "/api/*"
  to     = "https://arabic-miracle-api.onrender.com/:splat"
  status = 200
  force  = true

# 2) Serve index.html for everything else (Single-Page App)
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
