[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from   = "/analyze"
  to     = "https://arabic-miracle-api.onrender.com/analyze"
  status = 200
  force  = true

# ✅ Allow direct access to static pages
[[redirects]]
  from = "/about.html"
  to   = "/about.html"
  status = 200

[[redirects]]
  from = "/ads.html"
  to   = "/ads.html"
  status = 200

[[redirects]]
  from = "/contact.html"
  to   = "/contact.html"
  status = 200

[[redirects]]
  from = "/instructions.html"
  to   = "/instructions.html"
  status = 200

[[redirects]]
  from = "/links.html"
  to   = "/links.html"
  status = 200

[[redirects]]
  from = "/thank-you.html"
  to   = "/thank-you.html"
  status = 200
  force = true

# ✅ SPA fallback for everything else
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
