# netlify.toml

[build]
  publish = "build"            # or "dist" / whatever you use
  command = "npm run build"    # or "yarn build"

[[redirects]]
  from     = "/api/*"
  to       = "https://arabic-miracle-api.onrender.com/:splat"
  status   = 200
  force    = true
